/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.objectorientedpokemon.menu;

import com.mycompany.objectorientedpokemon.GameManager;
import java.awt.Color;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class MenuPanel extends javax.swing.JPanel {

    private java.awt.image.BufferedImage backgroundImage, logo;
    private GameManager gameM;
    
    /**
     * Creates new form StartPanel
     */
    public MenuPanel(GameManager gameM) {
        initComponents();
        
        this.gameM = gameM;
        try {
            backgroundImage = ImageIO.read(getClass().getResourceAsStream("/images/BG_main.png"));
            // logo = ImageIO.read(getClass().getResourceAsStream("/images/logo_pokemon.png"));
        } catch (Exception e) {
            e.printStackTrace();
        }
        setup();
        
        this.setPreferredSize(new java.awt.Dimension(1280, 720));
    }
    
    private void setup() {
        btnNewGame.setContentAreaFilled(false);
        btnNewGame.setOpaque(false);
        btnNewGame.setFocusPainted(false);
        btnNewGame.setBorder(null);
        
        btnLoadGame.setContentAreaFilled(false);
        btnLoadGame.setOpaque(false);
        btnLoadGame.setFocusPainted(false);
        btnLoadGame.setBorder(null);
        
        btnExitGame.setContentAreaFilled(false);
        btnExitGame.setOpaque(false);
        btnExitGame.setFocusPainted(false);
        btnExitGame.setBorder(null);
    }
    
    @Override
    protected void paintComponent(java.awt.Graphics g) {
        super.paintComponent(g);
        
        // Draw image first (so it is behind the buttons)
        if (backgroundImage != null) {
            g.drawImage(backgroundImage, 0, 0, 1280, 720, null);
            // g.drawImage(logo, 0, 0, 188 * 3, 105 * 3, this);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExitGame = new javax.swing.JButton();
        btnNewGame = new javax.swing.JButton();
        btnLoadGame = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1280, 720));

        btnExitGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btns/exit.png"))); // NOI18N
        btnExitGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitGameMouseClicked(evt);
            }
        });

        btnNewGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btns/new_game.png"))); // NOI18N
        btnNewGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewGameMouseClicked(evt);
            }
        });

        btnLoadGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btns/load.png"))); // NOI18N
        btnLoadGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoadGameMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_pokemon.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExitGame)
                    .addComponent(btnNewGame)
                    .addComponent(btnLoadGame))
                .addGap(529, 529, 529))
            .addGroup(layout.createSequentialGroup()
                .addGap(452, 452, 452)
                .addComponent(jLabel1)
                .addContainerGap(452, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(btnNewGame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLoadGame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExitGame)
                .addGap(123, 123, 123))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitGameMouseClicked
        // TODO add your handling code here:
        gameM.playSE(4);
        System.exit(0);
    }//GEN-LAST:event_btnExitGameMouseClicked

    private void btnNewGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewGameMouseClicked
        // TODO add your handling code here:
        gameM.showNewGame();
    }//GEN-LAST:event_btnNewGameMouseClicked

    private void btnLoadGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadGameMouseClicked
        // TODO add your handling code here:
//        JOptionPane.showMessageDialog(null, "Load game is not done yet...", "Sorry", JOptionPane.PLAIN_MESSAGE);
        if (gameM.player.myParty.isEmpty()) {
            gameM.showNewGame();
        } else {
            gameM.showMap();
        }
    }//GEN-LAST:event_btnLoadGameMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExitGame;
    private javax.swing.JButton btnLoadGame;
    private javax.swing.JButton btnNewGame;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
