/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.objectorientedpokemon.map;

import com.mycompany.objectorientedpokemon.GameConstants;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author User
 */
public class GamePanel extends javax.swing.JPanel implements Runnable {
    
    // Temp variable
    private int playerX = 100, playerY = 100, speed = 4;
    
    private KeyHandler keyH = new KeyHandler();
    private boolean isStopped;
    private Thread gameThread;
    
    /**
     * Creates new form GamePanel
     */
    public GamePanel() {
        initComponents();
        this.setBackground(Color.black);
        this.setDoubleBuffered(true);
        this.setPreferredSize(new Dimension(GameConstants.SCREEN_WIDTH, GameConstants.SCREEN_HEIGHT));
        
        this.addKeyListener(keyH);
        this.setFocusable(true);
        
        btnStop.setFocusable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStop = new javax.swing.JButton();

        btnStop.setText("Stop");
        btnStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStopMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnStop)
                .addContainerGap(312, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStop)
                .addContainerGap(271, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStopMouseClicked
        // TODO add your handling code here:
        isStopped = true;
        System.exit(0);
    }//GEN-LAST:event_btnStopMouseClicked

    @Override
    public void addNotify() {
        super.addNotify();
        // This method is called automatically when the panel is 
        // added to the JFrame and becomes displayable.
        if (gameThread == null) {
            startGameThread();
        }
        
        this.requestFocusInWindow();
    }
    
    @Override
    public void run() {
        double drawInterval = 1000000000 / 60; // 60 FPS
        double delta = 0;
        long lastTime = System.nanoTime();
        long currentTime;
        
        while (gameThread != null) { // Check gameThread, not just true

            currentTime = System.nanoTime();
            delta += (currentTime - lastTime) / drawInterval;
            lastTime = currentTime;

            if (delta >= 1) {
                if (!isStopped) { // Only update/repaint if not stopped
                    update();
                    repaint();
                }
                delta--;
            }

            if (isStopped) {
                 break; 
            }
        }
    }

    private void startGameThread() {
//        System.out.println("startGameThread() is running...");
        gameThread = new Thread(this);
        gameThread.start();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStop;
    // End of variables declaration//GEN-END:variables

    private void update() {
//        System.out.println("Update() is running...");
        if (keyH.upPressed) {
            playerY -= speed;
        } else if (keyH.downPressed) {
            playerY += speed;
        } else if (keyH.rightPressed) {
            playerX += speed;
        } else if (keyH.leftPressed) {
            playerX -= speed;
        }
    }
    
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
//        System.out.println("repaint() is running...");
        
        Graphics2D g2 = (Graphics2D) g;
        g2.setColor(Color.red);
        g2.fillRect(playerX, playerY, GameConstants.TILE_SIZE, GameConstants.TILE_SIZE);
        
        g2.dispose();
    }
}
