/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.objectorientedpokemon.map;

import com.mycompany.objectorientedpokemon.GameConstants;
import com.mycompany.objectorientedpokemon.GameManager;
import com.mycompany.objectorientedpokemon.map.mapEntity.MapEntity;
import com.mycompany.objectorientedpokemon.map.mapEntity.MapMonster;
import com.mycompany.objectorientedpokemon.map.mapEntity.MapPlayer;
import com.mycompany.objectorientedpokemon.map.tile.TileManager;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author User
 */
public class MapPanel extends javax.swing.JPanel implements Runnable {
    
    // SYSTEM
    private boolean isStopped;
    public boolean gameStateOn;
    private Thread gameThread;
    public GameManager gameM;
    public KeyHandler keyH = new KeyHandler(this);
    public TileManager tileM = new TileManager(this);
    public CollisionChecker cChecker = new CollisionChecker(this);
    public UiMap ui = new UiMap(this);
    public AssetSetter aSetter = new AssetSetter(this);
    public EventHandler eHandler = new EventHandler(this);
    
    // ENTITY
    public MapPlayer player = new MapPlayer(this, keyH);
    public MapMonster monster[] = new MapMonster[25];

    
    /**
     * Creates new form GamePanel
     */
    public MapPanel(GameManager gameM) {
        initComponents();
        this.gameM = gameM;
        this.setBackground(Color.gray);
        this.setDoubleBuffered(true);
        this.setPreferredSize(new Dimension(GameConstants.SCREEN_WIDTH, GameConstants.SCREEN_HEIGHT));
        
        this.addKeyListener(keyH);
        this.setFocusable(true);
        
        btnBackToMenu.setFocusable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBackToMenu = new javax.swing.JButton();

        btnBackToMenu.setText("Back to Menu");
        btnBackToMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackToMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnBackToMenu)
                .addContainerGap(281, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackToMenu)
                .addContainerGap(271, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackToMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackToMenuMouseClicked
        // TODO add your handling code here:
        gameThread = null;
        gameM.showMenu();
    }//GEN-LAST:event_btnBackToMenuMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToMenu;
    // End of variables declaration//GEN-END:variables

    public void setupGame() {
        gameStateOn = true;
        
        if (gameThread == null) {
            startGameThread();
        }
        
        this.requestFocusInWindow();
        aSetter.setMonster(25);
    }
    
    @Override
    public void addNotify() {
        super.addNotify();
        // This method is called automatically when the panel is 
        // added to the JFrame and becomes displayable.
        if (gameThread == null) {
            startGameThread();
        }
        
        this.requestFocusInWindow();
        gameStateOn = true;
        
    }
    
    @Override
    public void run() {
        double drawInterval = 1000000000 / 60; // 60 FPS
        double delta = 0;
        long lastTime = System.nanoTime();
        long currentTime;
        
        while (gameThread != null) { 

            currentTime = System.nanoTime();
            delta += (currentTime - lastTime) / drawInterval;
            lastTime = currentTime;
            if (delta >= 1) {
                if (gameStateOn) {
                    update();
                }
                repaint();
                delta--;
            }

        }
    }

    private void startGameThread() {
//        System.out.println("startGameThread() is running...");
        gameThread = new Thread(this);
        gameThread.start();
    }
    
    private void update() {
//        System.out.println("Update() is running...");
        if (gameStateOn) {
            player.update();
        } else {
            //
        }
    }
    
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
//        System.out.println("repaint() is running...");
        
        Graphics2D g2 = (Graphics2D) g;
        
        tileM.draw(g2);
        player.draw(g2);
        System.out.println(player.worldX);
        System.out.println(player.worldY);
        
        for (MapMonster elem : monster) {
            if (elem != null) {
                elem.draw(g2);
            }
        }
        
        ui.draw(g2);

    }
}
